### ISSUE TITLE
Create dark mode option.

### ISSUE THREAD

**Issue by jaideepghosh** [OffPe/react-covid19-stats#10]
Lets create a dark mode toggle switch in the top right corner. It should add dark mode class in the body and based on which the background and text color should switch from light to dark theme.

**Comment by yigitcukuren** [comment]
Hi @jaideepghosh,

Hello, I would to love work on this, can you please assign to me?

**Comment by jaideepghosh** [comment]
Hey @yigitcukuren 
I'm assigning this to you. Happy coding 🎉
