### ISSUE TITLE
Issue with manifest. So PWA installation is not working. 

### ISSUE THREAD

**Issue by vj-abishek** [OffPe/react-covid19-stats#26]
![Annotation 2020-10-03 121502](https://user-images.githubusercontent.com/43115551/94985302-1cf30a80-0573-11eb-9f60-24c83bcfb8d6.jpg)

@jaideepghosh You are using "browser"

>  browser  - A standard browser experience

https://web.dev/add-manifest/

**Comment by Nithin005** [comment]
I have fixed the issue in PR

**Comment by jaideepghosh** [comment]
Related changes are merged to development branch.
