### ISSUE TITLE
Add offline PWA support

### ISSUE THREAD

**Issue by jaideepghosh** [OffPe/react-covid19-stats#8]
Configure the app to support PWA, and Create an offline screen to show when the device goes offline.

**Comment by vj-abishek** [comment]
Can I work on it?

**Comment by jaideepghosh** [comment]
Great @vj-abishek Assigning it to you.

**Comment by vj-abishek** [comment]
@jaideepghosh  you already enabled service-worker in CRA. Do I need to create offline screen?

**Comment by vj-abishek** [comment]
@jaideepghosh Do you like a tooltip or a full offline page? For the Offline Screen.

**Comment by jaideepghosh** [comment]
Yes
